import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import type { WeeklyWinDto } from '../../types/api'
import { generateWeeklyWins } from '../../api/ai'
import { Card } from '../common/Card'
import { EmptyState } from '../common/EmptyState'
import { PillButton } from '../common/PillButton'
import { qk } from '../../lib/queryKeys'

function formatWeekLabel(weekFrom: string, weekTo: string): string {
  const from = new Date(`${weekFrom}T00:00:00`)
  const to = new Date(`${weekTo}T00:00:00`)
  const fromLabel = from.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
  const toLabel = to.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
  return weekFrom === weekTo ? fromLabel : `${fromLabel} – ${toLabel}`
}

/** One week's win: a short prose sentence plus its point-wise genuine wins. */
function WeekCard({ win }: { win: WeeklyWinDto }) {
  return (
    <div className="flex flex-col gap-2 border-b border-line pb-4 last:border-b-0 last:pb-0">
      <span className="text-[11px] uppercase tracking-wide text-faint">{formatWeekLabel(win.weekFrom, win.weekTo)}</span>
      <p className="text-sm leading-relaxed text-ink">{win.summary}</p>
      {win.highlights.length > 0 && (
        <ul className="flex flex-col gap-1 pl-4 text-sm text-muted">
          {win.highlights.map((h, i) => (
            <li key={i} className="list-disc marker:text-accent">
              {h}
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

/**
 * "Story of the month" — one prose sentence plus point-wise genuine wins per
 * calendar week, generated by Job C run once per week (see WeeklyWinRunner).
 * Explicitly triggered, never on page load — same discipline as narrate.
 */
export function WeeklyWinList({ from, to, wins }: { from: string; to: string; wins: WeeklyWinDto[] }) {
  const [confirming, setConfirming] = useState(false)
  const queryClient = useQueryClient()

  const mutation = useMutation({
    mutationFn: () => generateWeeklyWins({ from, to }),
    onSuccess: () => {
      setConfirming(false)
      queryClient.invalidateQueries({ queryKey: qk.weeklyWins(from, to) })
    },
  })

  const hasExisting = wins.length > 0
  const stoppedEarly = mutation.data?.stoppedEarly
  const button = confirming ? (
    <div className="flex flex-col items-end gap-2">
      <p className="max-w-md text-right text-xs text-faint">
        This calls the model once per week — a handful of calls, roughly a minute. Session narratives for this
        month leave this machine.
      </p>
      <div className="flex gap-2">
        <PillButton onClick={() => mutation.mutate()} disabled={mutation.isPending}>
          {mutation.isPending ? 'Summarizing…' : hasExisting ? 'Update the wins' : 'Summarize weeks'}
        </PillButton>
        <PillButton onClick={() => setConfirming(false)} disabled={mutation.isPending}>
          Cancel
        </PillButton>
      </div>
    </div>
  ) : (
    <PillButton onClick={() => setConfirming(true)}>{hasExisting ? 'Update the wins' : 'Summarize weeks'}</PillButton>
  )

  if (wins.length === 0) {
    return (
      <EmptyState title="No weekly wins written for this month yet." detail="Summarizes each week's stories into one short win.">
        <div className="mt-3 flex justify-center">{button}</div>
      </EmptyState>
    )
  }

  return (
    <Card className="flex flex-col gap-4 p-4">
      <div className="flex items-start justify-between gap-4">
        <span className="text-xs text-faint">Story of the month</span>
        {button}
      </div>
      {stoppedEarly && (
        <p className="text-xs text-warn">
          Stopped early — provider rate limit reached: {mutation.data?.stopReason}. Remaining weeks are
          untouched; run again later to pick them up.
        </p>
      )}
      <div className="flex flex-col gap-4">
        {wins.map((w) => (
          <WeekCard key={`${w.weekFrom}-${w.weekTo}`} win={w} />
        ))}
      </div>
    </Card>
  )
}
