using System.Text.Json;
using System.Text.Json.Serialization;
using Devlog.Core.Abstractions;
using Devlog.Core.Ai;
using Devlog.Core.Configuration;
using Devlog.Core.Domain;
using Devlog.Core.Metrics;
using Microsoft.Extensions.Logging;

namespace Devlog.Host.Ai;

public sealed record AskResult(
    bool Success,
    string? Answer,
    string? Model,
    int ToolRounds,
    IReadOnlyList<string> ToolsUsed,
    IReadOnlyList<string> UnverifiedNumbers,
    string? Error);

public sealed class AskRunner(
    IChatClient chatClient,
    ISessionReader sessionReader,
    INarrativeStore narrativeStore,
    IClassificationRuleStore ruleStore,
    AiOptions options,
    ILogger<AskRunner> logger)
{
    private const int MaxToolRounds = 5;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    public async Task<AskResult> AskAsync(
        string question,
        bool quiet = false,
        CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(question))
        {
            return new AskResult(false, null, null, 0, [], [], "Question cannot be empty.");
        }

        var reachable = await chatClient.IsReachableAsync(ct).ConfigureAwait(false);
        if (!reachable)
        {
            return new AskResult(false, null, null, 0, [], [], "AI provider is not reachable. Run 'devlog llm' to diagnose.");
        }

        var now = DateTimeOffset.UtcNow;
        var systemPrompt = AskPrompt.GetSystemPrompt(now);

        var messages = new List<ChatMessage>
        {
            new("system", systemPrompt),
            new("user", question)
        };

        var toolsUsed = new List<string>();
        var toolOutputs = new List<string>();
        string? finalAnswer = null;
        string? usedModel = options.Model;
        var rounds = 0;

        for (int round = 0; round < MaxToolRounds; round++)
        {
            rounds++;
            var result = await chatClient.CompleteWithToolsAsync(
                messages,
                AskPrompt.Tools,
                AskPrompt.ReasoningEffort,
                ct).ConfigureAwait(false);

            if (!result.Reachable || result.Message is null)
            {
                return new AskResult(false, null, result.Model, rounds, toolsUsed, [], result.Error ?? "Empty response from model.");
            }

            usedModel = result.Model ?? usedModel;
            var assistantMsg = result.Message;
            messages.Add(assistantMsg);

            // If no tool calls, model gave the final answer
            if (assistantMsg.ToolCalls is null or { Count: 0 })
            {
                finalAnswer = assistantMsg.Content;
                break;
            }

            // Execute each requested tool call
            foreach (var tc in assistantMsg.ToolCalls)
            {
                var fnName = tc.Function.Name;
                toolsUsed.Add(fnName);
                if (!quiet)
                {
                    logger.LogInformation("Tool call: {Name}({Args})", fnName, tc.Function.Arguments);
                }

                var outputJson = await ExecuteToolAsync(fnName, tc.Function.Arguments, ct).ConfigureAwait(false);
                toolOutputs.Add(outputJson);

                messages.Add(new ChatMessage("tool", outputJson, tc.Id));
            }
        }

        // If loop finished without content (e.g. capped at 5 rounds of tool calls), do a final non-tool completion
        if (string.IsNullOrWhiteSpace(finalAnswer))
        {
            var finalCompletion = await chatClient.CompleteWithToolsAsync(
                messages,
                null, // No tools in final force-answer turn
                AskPrompt.ReasoningEffort,
                ct).ConfigureAwait(false);

            finalAnswer = finalCompletion.Message?.Content ?? "(No final answer generated by model)";
        }

        // Numeric hallucination defense
        AskPrompt.VerifyNumbers(finalAnswer, toolOutputs, out var unverifiedNumbers);
        if (unverifiedNumbers.Count > 0)
        {
            logger.LogWarning("Potential numeric hallucination detected in answer: {Tokens}", string.Join(", ", unverifiedNumbers));
        }

        return new AskResult(
            Success: true,
            Answer: finalAnswer,
            Model: usedModel,
            ToolRounds: rounds,
            ToolsUsed: toolsUsed,
            UnverifiedNumbers: unverifiedNumbers,
            Error: null);
    }

    private async Task<string> ExecuteToolAsync(string toolName, string argumentsJson, CancellationToken ct)
    {
        try
        {
            using var doc = JsonDocument.Parse(string.IsNullOrWhiteSpace(argumentsJson) ? "{}" : argumentsJson);
            var root = doc.RootElement;

            switch (toolName)
            {
                case "getSessions":
                {
                    var fromIso = GetString(root, "fromIso");
                    var toIso = GetString(root, "toIso");
                    var project = GetString(root, "project");
                    var category = GetString(root, "category");

                    var fromUtc = ParseIsoToUtcMillis(fromIso, DateTimeOffset.UtcNow.AddDays(-7).ToUnixTimeMilliseconds());
                    var toUtc = ParseIsoToUtcMillis(toIso, DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());

                    var sessions = await sessionReader.GetRangeAsync(fromUtc, toUtc, ct).ConfigureAwait(false);

                    if (!string.IsNullOrWhiteSpace(project))
                    {
                        sessions = sessions.Where(s => string.Equals(s.Session.Project, project, StringComparison.OrdinalIgnoreCase)).ToList();
                    }

                    if (!string.IsNullOrWhiteSpace(category) && ActivityCategoryExtensions.TryParse(category, out var catEnum))
                    {
                        sessions = sessions.Where(s => s.Session.Category == catEnum).ToList();
                    }

                    var capped = sessions.Take(200).Select(s => new
                    {
                        s.Session.Id,
                        Start = s.Session.Start.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                        End = s.Session.End.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                        DurationMinutes = s.Session.DurationSeconds / 60,
                        DeepMinutes = s.Session.DeepSeconds / 60,
                        s.Session.Project,
                        Category = s.Session.Category.ToString(),
                        s.ActivityCount,
                        s.CommitCount,
                        s.Session.Label
                    }).ToList();

                    return JsonSerializer.Serialize(new
                    {
                        TotalFound = sessions.Count,
                        Returned = capped.Count,
                        Sessions = capped
                    }, JsonOptions);
                }

                case "getSessionDetail":
                {
                    var sessionId = GetLong(root, "sessionId");
                    var summary = await sessionReader.GetByIdAsync(sessionId, ct).ConfigureAwait(false);
                    if (summary is null)
                    {
                        return JsonSerializer.Serialize(new { Error = $"Session {sessionId} not found." }, JsonOptions);
                    }

                    var activities = await sessionReader.GetActivitiesAsync(sessionId, ct).ConfigureAwait(false);
                    var commits = await sessionReader.GetCommitsForSessionAsync(sessionId, ct).ConfigureAwait(false);

                    return JsonSerializer.Serialize(new
                    {
                        Session = new
                        {
                            summary.Session.Id,
                            Start = summary.Session.Start.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                            End = summary.Session.End.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                            DurationMinutes = summary.Session.DurationSeconds / 60,
                            summary.Session.Project,
                            Category = summary.Session.Category.ToString(),
                            summary.Session.Label
                        },
                        Activities = activities.Select(a => new
                        {
                            Start = a.Start.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                            DurationSeconds = a.DurationSeconds,
                            a.ProcessName,
                            a.SiteIdentity,
                            a.SampleTitle,
                            Category = a.Category.ToString()
                        }),
                        Commits = commits.Select(c => new
                        {
                            c.Sha,
                            c.Message,
                            c.Repo,
                            c.Branch,
                            c.FilesChanged,
                            c.Insertions,
                            c.Deletions
                        })
                    }, JsonOptions);
                }

                case "getCommits":
                {
                    var fromIso = GetString(root, "fromIso");
                    var toIso = GetString(root, "toIso");
                    var project = GetString(root, "project");

                    var fromUtc = ParseIsoToUtcMillis(fromIso, DateTimeOffset.UtcNow.AddDays(-7).ToUnixTimeMilliseconds());
                    var toUtc = ParseIsoToUtcMillis(toIso, DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());

                    var commits = await sessionReader.GetCommitsAsync(fromUtc, toUtc, ct).ConfigureAwait(false);
                    if (!string.IsNullOrWhiteSpace(project))
                    {
                        commits = commits.Where(c => string.Equals(c.Project, project, StringComparison.OrdinalIgnoreCase) ||
                                                     string.Equals(c.Repo, project, StringComparison.OrdinalIgnoreCase)).ToList();
                    }

                    var capped = commits.Take(200).Select(c => new
                    {
                        c.Sha,
                        Timestamp = DateTimeOffset.FromUnixTimeMilliseconds(c.TsUtc).ToString("yyyy-MM-ddTHH:mm:ssZ"),
                        c.Repo,
                        c.Project,
                        c.Message,
                        c.Branch,
                        c.FilesChanged,
                        c.Insertions,
                        c.Deletions,
                        c.IsMerge,
                        c.SessionId
                    }).ToList();

                    return JsonSerializer.Serialize(new
                    {
                        TotalFound = commits.Count,
                        Returned = capped.Count,
                        Commits = capped
                    }, JsonOptions);
                }

                case "getMetrics":
                {
                    var fromIso = GetString(root, "fromIso");
                    var toIso = GetString(root, "toIso");

                    var fromDate = ParseIsoToDateOnly(fromIso, DateOnly.FromDateTime(DateTime.UtcNow.AddDays(-7)));
                    var toDate = ParseIsoToDateOnly(toIso, DateOnly.FromDateTime(DateTime.UtcNow));

                    var (metrics, _) = await DigestBuilder.BuildAsync(sessionReader, fromDate, toDate, ct).ConfigureAwait(false);

                    return JsonSerializer.Serialize(new
                    {
                        metrics.From,
                        metrics.To,
                        TrackedHours = Math.Round(metrics.TrackedSeconds / 3600.0, 1),
                        DeepHours = Math.Round(metrics.DeepSeconds / 3600.0, 1),
                        metrics.FocusRatio,
                        metrics.SessionCount,
                        metrics.ActiveDays,
                        metrics.CommitCount,
                        metrics.Insertions,
                        metrics.Deletions,
                        Projects = metrics.TimeByProject.Select(p => new { p.Project, Hours = Math.Round(p.Seconds / 3600.0, 1) }),
                        Categories = metrics.TimeByCategory.Select(c => new { Category = c.Category.ToString(), Hours = Math.Round(c.Seconds / 3600.0, 1) })
                    }, JsonOptions);
                }

                case "getNarratives":
                {
                    var fromIso = GetString(root, "fromIso");
                    var toIso = GetString(root, "toIso");

                    var fromUtc = ParseIsoToUtcMillis(fromIso, DateTimeOffset.UtcNow.AddDays(-7).ToUnixTimeMilliseconds());
                    var toUtc = ParseIsoToUtcMillis(toIso, DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());

                    var narratives = await narrativeStore.GetRangeAsync(fromUtc, toUtc, ct).ConfigureAwait(false);

                    return JsonSerializer.Serialize(narratives.Select(n => new
                    {
                        SessionStart = DateTimeOffset.FromUnixTimeMilliseconds(n.SessionStartUtc).ToString("yyyy-MM-ddTHH:mm:ssZ"),
                        SessionEnd = DateTimeOffset.FromUnixTimeMilliseconds(n.SessionEndUtc).ToString("yyyy-MM-ddTHH:mm:ssZ"),
                        n.SessionId,
                        n.Kind,
                        n.Workstream,
                        n.Narrative,
                        n.Evidence,
                        n.Confidence,
                        n.Model
                    }), JsonOptions);
                }

                case "getPendingIdentities":
                {
                    var allRules = await ruleStore.GetAllAsync(ct).ConfigureAwait(false);
                    var pending = new List<object>();
                    foreach (var r in allRules.Where(r => r.IsPending))
                    {
                        var samples = await ruleStore.GetSampleTitlesAsync(r.Site, 3, ct).ConfigureAwait(false);
                        pending.Add(new
                        {
                            Identity = r.Site,
                            r.Hits,
                            Seconds = r.TotalSeconds,
                            Category = r.Category?.ToString() ?? "Unknown",
                            SampleTitles = samples
                        });
                    }

                    return JsonSerializer.Serialize(pending, JsonOptions);
                }

                default:
                    return JsonSerializer.Serialize(new { Error = $"Unknown tool '{toolName}'." }, JsonOptions);
            }
        }
        catch (Exception ex)
        {
            return JsonSerializer.Serialize(new { Error = $"Tool execution error: {ex.Message}" }, JsonOptions);
        }
    }

    private static string? GetString(JsonElement root, string propName) =>
        root.TryGetProperty(propName, out var prop) && prop.ValueKind == JsonValueKind.String ? prop.GetString() : null;

    private static long GetLong(JsonElement root, string propName) =>
        root.TryGetProperty(propName, out var prop) && prop.TryGetInt64(out var val) ? val : 0;

    private static long ParseIsoToUtcMillis(string? iso, long fallback)
    {
        if (!string.IsNullOrWhiteSpace(iso) && DateTimeOffset.TryParse(iso, out var dto))
        {
            return dto.ToUnixTimeMilliseconds();
        }
        return fallback;
    }

    private static DateOnly ParseIsoToDateOnly(string? iso, DateOnly fallback)
    {
        if (!string.IsNullOrWhiteSpace(iso) && DateOnly.TryParse(iso, out var d))
        {
            return d;
        }
        if (!string.IsNullOrWhiteSpace(iso) && DateTimeOffset.TryParse(iso, out var dto))
        {
            return DateOnly.FromDateTime(dto.DateTime);
        }
        return fallback;
    }
}
